name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Restore credentials
        run: |
          echo "${{ secrets.CLASP_CLIENT_SECRET }}" | base64 -d > client_secret.json
          echo "${{ secrets.CLASP_RC }}" | base64 -d > ~/.clasprc.json

      - name: Set project ID
        run: clasp setting projectId ${{ secrets.CLASP_PROJECT_ID }}

      - name: Deploy to Apps Script
        run: clasp push
